<?php

/**
 * @file
 * Install, update and uninstall functions for the Extended Logger module.
 */

/**
 * Add the service_name configuration key.
 */
function extended_logger_update_10001(): void {
  \Drupal::configFactory()->getEditable('extended_logger.settings')
    ->set('service_name', '')
    ->save(TRUE);
}

/**
 * Add the log_line_max_length configuration key.
 */
function extended_logger_update_10002(): void {
  \Drupal::configFactory()->getEditable('extended_logger.settings')
    ->set('log_line_max_length', NULL)
    ->save(TRUE);
}

/**
 * Set the backlog_items_limit configuration key.
 */
function extended_logger_update_10003(): void {
  \Drupal::configFactory()->getEditable('extended_logger.settings')
    ->set('backlog_items_limit', NULL)
    ->save(TRUE);
}

/**
 * Migrate config to new format: join custom fields, entry_exclude_empty.
 */
function extended_logger_update_10004(): void {
  $config = \Drupal::configFactory()->getEditable('extended_logger.settings');
  $fields = $config->get('fields') ?? [];
  $fieldsCustom = $config->get('fields_custom') ?? [];
  array_push($fields, ...$fieldsCustom);
  $fields = array_unique($fields);
  $config->set('fields', array_values($fields));
  $config->clear('fields_custom');
  $config->set('entry_exclude_empty', FALSE);
  $config->save(TRUE);
}
