extended_logger.settings:
  type: config_object
  label: Extended Logger
  mapping:
    fields:
      type: sequence
      label: Enabled fields
      sequence:
        type: string
        label: Field name
    fieldsCustom:
      type: sequence
      label: Additional custom fields to include
      sequence:
        type: string
        label: Field name
    target:
      type: string
      label: Log target
    targetSyslogIdentity:
      type: string
      label: Syslog identity
    targetSyslogFacility:
      type: integer
      label: Syslog facility
    targetFileTarget:
      type: string
      label: Path to the log file
    targetOutputStream:
      type: string
      label: Output stream
