extended_logger.settings:
  type: config_object
  label: Extended Logger
  mapping:
    fields:
      type: sequence
      label: Enabled fields
      sequence:
        type: string
        label: Field name
    fields_all:
      type: boolean
      label: Add all fields to logs
    fields_custom:
      type: sequence
      label: Additional custom fields to include
      sequence:
        type: string
        label: Field name
    target:
      type: string
      label: Log target
    target_syslog_identity:
      type: string
      label: Syslog identity
    target_syslog_facility:
      type: integer
      label: Syslog facility
    target_file_path:
      type: string
      label: Path to the log file
    target_output_stream:
      type: string
      label: Output stream
